name: Build on DockerHub and Deploy to AWS
on:
  workflow_dispatch:
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: rlavoisier/fastapitest:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_DNS }} 'sudo docker pull rlavoisier/fastapitest:latest'
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_DNS }} 'sudo docker stop my-fastapi-container || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_DNS }} 'sudo docker rm my-fastapi-container || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_DNS }} 'sudo run -d --name my-fastapi-container -p 8000:8000 rlavoisier/fastapitest:latest'
